### ISSUE TITLE
Minimal packages required?

### ISSUE THREAD

**Issue by mishoboss** [liske/barkery#3]
Hi, I try to run barkery on both Raspbian and Orange Pi Debian distros without GUI, but unsuccessfully so far. I see you use Weston/Wayland and I tried with it, as well as X server, but no success. I get error that server is not found. What do you use and how you run it? The idea is to have a very minimal setup with lightweight window manager just running barkery and nothing else.

**Comment by liske** [comment]
I've packaged it for Alpine Linux, maybe you could adopt it for your setup: https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/barkery
